//go:build ignore

// gen_sdk_header.go — embed ios_sdk_rules.json into the dylib as an
// AES-256-CTR-encrypted C byte array, so the SDK detection rules no longer ship
// as a loose, world-readable /var/mobile/monitor_sdk_rules.json on device.
//
// AES-256-CTR (not XOR): the rules are a 116 KB JSON whose structure is fully
// known ({"name":,"class":,...}), so a repeating-XOR key would fall to a
// known-plaintext attack instantly. CTR gives ciphertext == plaintext length,
// no padding, and matches the dex/asset encryption used elsewhere. Blob layout
// is [16-byte IV][ciphertext]; the key ships in the header (extractable on a
// jailbroken device — this raises the `strings`/file-copy bar, it is not a
// cryptographic secret; rotate per release with the other keys).
//
// Usage (run where the canonical JSON lives, e.g. pecker-agent):
//
//	go run tools/gen_sdk_header.go ../pecker-agent/scripts/ios_sdk_rules.json SDKRulesData.h
//
// Tweak.x decrypts the blob with CommonCrypto AES-CTR (same key, IV from the
// blob head). Re-run and commit SDKRulesData.h whenever ios_sdk_rules.json changes.
package main

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"fmt"
	"io"
	"os"
)

// MUST match kSDKRulesKey emitted into SDKRulesData.h (this tool writes it there).
var key = []byte{
	0xb6, 0xd3, 0x63, 0x61, 0xed, 0xfb, 0x0a, 0x15,
    0xa6, 0xaa, 0x45, 0x9d, 0x19, 0xd0, 0x88, 0xd4,
    0xdf, 0x5c, 0x04, 0x99, 0x32, 0xe3, 0xa8, 0xa7,
    0x6c, 0x72, 0x12, 0xe0, 0x45, 0x57, 0x9a, 0x78,
}

func ctrXor(dst, src, iv []byte) {
	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err)
	}
	cipher.NewCTR(block, iv).XORKeyStream(dst, src)
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: go run gen_sdk_header.go <in.json> <out.h>")
		os.Exit(2)
	}
	plain, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", os.Args[1], err)
		os.Exit(1)
	}

	iv := make([]byte, 16)
	if _, err := io.ReadFull(rand.Reader, iv); err != nil {
		fmt.Fprintf(os.Stderr, "rng: %v\n", err)
		os.Exit(1)
	}
	ct := make([]byte, len(plain))
	ctrXor(ct, plain, iv)

	// Self-check: decrypt must reproduce the input byte-for-byte.
	back := make([]byte, len(ct))
	ctrXor(back, ct, iv)
	if !bytes.Equal(back, plain) {
		fmt.Fprintln(os.Stderr, "FATAL: CTR roundtrip mismatch")
		os.Exit(1)
	}

	blob := append(append([]byte{}, iv...), ct...) // [16B IV][ciphertext]

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Generated by tools/gen_sdk_header.go — DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s (%d bytes plaintext). AES-256-CTR, blob = [16B IV][ciphertext].\n", os.Args[1], len(plain))
	fmt.Fprintf(&b, "#ifndef SDK_RULES_DATA_H\n#define SDK_RULES_DATA_H\n#include <stdint.h>\n\n")
	writeArray(&b, "kSDKRulesKey", key)
	writeArray(&b, "kSDKRulesBlob", blob)
	fmt.Fprintf(&b, "static const unsigned int kSDKRulesBlobLen = %d;\n\n", len(blob))
	fmt.Fprintf(&b, "#endif\n")

	if err := os.WriteFile(os.Args[2], b.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", os.Args[2], err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen_sdk_header: %d bytes JSON -> %s (blob %d bytes, roundtrip OK)\n",
		len(plain), os.Args[2], len(blob))
}

func writeArray(b *bytes.Buffer, name string, data []byte) {
	fmt.Fprintf(b, "static const uint8_t %s[%d] = {\n", name, len(data))
	for i, v := range data {
		if i%16 == 0 {
			b.WriteString("    ")
		}
		fmt.Fprintf(b, "0x%02x,", v)
		if i%16 == 15 {
			b.WriteString("\n")
		} else {
			b.WriteString(" ")
		}
	}
	if len(data)%16 != 0 {
		b.WriteString("\n")
	}
	b.WriteString("};\n\n")
}
